### PR TITLE
Fixed 'EOF' error on OS X

### PR DESCRIPTION
**Pull request by hunse**
See issue #51 for a full description of the error. The fix is to
add a scalar argument to the dummy kernel used by `plan.py:Marker`.

Hopefully this works. @jgosmann, can you check and make sure this fixes the problem on OS X?

### CODE REVIEW

**Comment by jgosmann** [comment]
That fixes the original "No kernels or only kernel prototypes found when build executable." error. Now everything fails with "LogicError: clEnqueueNDRangeKernel failed: invalid work group size".

```
____________ test.nengo.tests.test_connection.test_slicing_function ____________

Simulator = <function OclSimulator at 0x10dd8c5f0>
plt = <nengo.utils.testing.Mock object at 0x10ec956d0>, seed = 514211999

    def test_slicing_function(Simulator, plt, seed):
        """Test using a pre-slice and a function"""
        N = 300
        f_in = lambda t: [np.cos(3*t), np.sin(3*t)]
        f_x = lambda x: [x, -x**2]

        with nengo.Network(seed=seed) as model:
            u = nengo.Node(output=f_in)
            a = nengo.Ensemble(N, 2, radius=np.sqrt(2))
            b = nengo.Ensemble(N, 2, radius=np.sqrt(2))
            nengo.Connection(u, a)
            nengo.Connection(a[1], b, function=f_x)

            up = nengo.Probe(u, synapse=0.03)
            bp = nengo.Probe(b, synapse=0.03)

        sim = Simulator(model)
>       sim.run(1.)

../nengo/nengo/tests/test_connection.py:511:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
nengo_ocl/sim_npy.py:850: in run
    self.run_steps(steps)
nengo_ocl/sim_ocl.py:342: in run_steps
    self._dag.call_n_times(B)
nengo_ocl/plan.py:138: in call_n_times
    last_ev, all_evs = self.enqueue_n_times(n)
nengo_ocl/plan.py:152: in enqueue_n_times
    return self._enqueue_n_times_serial(n)
nengo_ocl/plan.py:159: in _enqueue_n_times_serial
    ev = plan.enqueue()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <nengo_ocl.plan.Plan object at 0x10f320110>, wait_for = None

    def enqueue(self, wait_for=None):
        ev = cl.enqueue_nd_range_kernel(
            self.queue, self.kern, self.gsize, self.lsize,
>           wait_for=wait_for)
E       LogicError: clEnqueueNDRangeKernel failed: invalid work group size

nengo_ocl/plan.py:86: LogicError
```

**Comment by hunse** [comment]
Okay, I'll have to look at your machine to see what plan is actually throwing this. Also, do you have NVIDIA and Intel OCL installed on your system? If you do, I'd be curious to know if this happens with either context or just with one.

Actually, the other thing you could print to help debug this is `self.queue.device.max_work_group_size`, and compare it to `self.lsize`. It should be <= `np.prod(self.lsize)`.

**Comment by jgosmann** [comment]
With the added commit (and setting `PYOPENCL_CTX=2` to use my Nvidia card instead of the CPU) all the tests run.

**Comment by jgosmann** [comment]
test_clra_nonlinearities still fails for the Intel Iris card, but with a different error than the CPU:
```______________________________________________________________ test_lif_step[4-7] _______________________________________________________________

upsample = 4, n_elements = 7

    @pytest.mark.parametrize(
        "upsample, n_elements", [(1, 0), (1, 6), (4, 0), (4, 7)])
    def test_lif_step(upsample, n_elements):
        """Test the lif nonlinearity, comparing one step with the Numpy version."""
        rng = np.random

        dt = 1e-3
        n_neurons = [12345, 23456, 34567]
        J = RA([rng.normal(scale=1.2, size=n) for n in n_neurons])
        V = RA([rng.uniform(low=0, high=1, size=n) for n in n_neurons])
        W = RA([rng.uniform(low=-5 * dt, high=5 * dt, size=n) for n in n_neurons])
        OS = RA([np.zeros(n) for n in n_neurons])

        ref = 2e-3
        taus = list(rng.uniform(low=15e-3, high=80e-3, size=len(n_neurons)))

        queue = cl.CommandQueue(ctx)
        clJ = CLRA(queue, J)
        clV = CLRA(queue, V)
        clW = CLRA(queue, W)
        clOS = CLRA(queue, OS)
        clTau = CLRA(queue, RA(taus))

        # simulate host
        nls = [LIF(tau_ref=ref, tau_rc=taus[i])
               for i, n in enumerate(n_neurons)]
        for i, nl in enumerate(nls):
            if upsample <= 1:
                nl.step_math(dt, J[i], OS[i], V[i], W[i])
            else:
                s = np.zeros_like(OS[i])
                for j in xrange(upsample):
                    nl.step_math(dt / upsample, J[i], s, V[i], W[i])
                    OS[i] = (1./dt) * ((OS[i] > 0) | (s > 0))

        # simulate device
        plan = plan_lif(queue, clJ, clV, clW, clV, clW, clOS, ref, clTau, dt,
>                       n_elements=n_elements, upsample=upsample)

nengo_ocl/tests/test_clra_nonlinearities.py:61:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
nengo_ocl/clra_nonlinearities.py:437: in plan_lif
    inputs=inputs, outputs=outputs, parameters=parameters)
nengo_ocl/clra_nonlinearities.py:700: in _plan_template
    _fn = cl.Program(queue.context, text).build().fn
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyopencl/__init__.py:166: in build
    options=options, source=self._source)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pyopencl.Program object at 0x10f8ed410>, build_func = <function <lambda> at 0x10f740398>
options = ['-I', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyopencl/cl']
source = '\n        ////////// MAIN FUNCTION //////////\n        __kernel void fn(\n            __global const int *j_starts,\n... ABOVE ^^^^^\n\n            *cur_ow = ow;\n            *cur_ov = ov;\n            *cur_os = os;\n\n        }\n        '

    def _build_and_catch_errors(self, build_func, options, source=None):
        try:
            return build_func()
        except _cl.RuntimeError, e:
            from pytools import Record

            class ErrorRecord(Record):
                pass

            what = e.what
            if options:
                what = what + "\n(options: %s)" % " ".join(options)

            if source is not None:
                from tempfile import NamedTemporaryFile
                srcfile = NamedTemporaryFile(mode="wt", delete=False, suffix=".cl")
                try:
                    srcfile.write(source)
                finally:
                    srcfile.close()

                what = what + "\n(source saved as %s)" % srcfile.name

            code = e.code
            routine = e.routine

            err = _cl.RuntimeError(
                    ErrorRecord(
                        what=lambda: what,
                        code=lambda: code,
                        routine=lambda: routine))

        # Python 3.2 outputs the whole list of currently active exceptions
        # This serves to remove one (redundant) level from that nesting.
>       raise err
E       RuntimeError: clBuildProgram failed: build program failure -
E
E       Build on <pyopencl.Device 'Iris Pro' on 'Apple' at 0x1024500>:
E
E       Compile Server Error.
E       (options: -I /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyopencl/cl)
E       (source saved as /var/folders/t7/99gtw6151wz7r76dzhxl08vr0000gn/T/tmpnl0XEP.cl)
```

Not sure how much we care about that ... it runs on the workhorse graphics card which is the important part.

**Comment by hunse** [comment]
Okay, I added a commit to hopefully help avoid type errors like this last one in the future. @jgosmann, can you confirm that I haven't broken anything on your Mac?

**Comment by jgosmann** [comment]
Works fine. :cake:

**Comment by hunse** [comment]
I'm not sure about that error on the Iris card. Maybe try it with fewer neurons? Since all the Nengo tests pass, I'm not too worried (i.e. the basic functionality is there). Also, it's interesting that it's just with those particular parameters. One of those parameters happens to be upsampling, which is something that we rarely/never use (I'm not even sure if there's a way to enable it in the API), so again I'm not too worried.

**Comment by tbekolay** [comment]
I'm trying this now on my Mac and most tests fail with
```
E       LogicError: clEnqueueNDRangeKernel failed: invalid work group size
```
On my Macbook, the GPU doesn't work with OpenCL, so I just have the following device:
```
Device Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz supports OpenCL 1.2
```

**Comment by hunse** [comment]
@jgosmann, is this the same error you were getting on your CPU? I remember you had some error, and I think that was it.

My diagnosis was that the Intel OCL drivers that come with Macs are a bit out of date, and don't support three dimensional kernels, which we use. Is there any way that you can upgrade the driver? The instructions in the README might help a bit, though of course they're for Linux.

**Comment by jgosmann** [comment]
Yeah, it's the same error.
I don't know if theres the possibility to upgrade the driver and I don't want to mess with that stuff. I'm too afraid that it will lead to [this](https://xkcd.com/349/). :fearful:

**Comment by hunse** [comment]
Haha, yeah... when I installed the Intel OCL driver on Linux, it was just
the OCL driver, so no mucking with the kernel and therefore no risk. But
definitely don't risk anything trying to get this working, especially
because if you have multi-core BLAS running already through Numpy, Nengo
OCL is not going to be any faster on your CPU.

Taking a quick look at Intel's website, it doesn't seem like there's any
updated OS X drivers readily available. This page
<https://software.intel.com/en-us/intel-opencl>, which is where the link in
the README now redirects, says that "OpenCL support is now integrated into
Intel’s software development suites" which I think means that you have to
pay for it. It says that OCL drivers ship with Intel products, but it
doesn't say anything about updated drivers. This page
<https://software.intel.com/en-us/articles/opencl-drivers> seems to have
some links to drivers, but they're all Windows or Linux.

**Comment by tbekolay** [comment]
Did a bit of digging... apparently 3-dimensional kernels aren't the problem ([Mac dev thing](https://developer.apple.com/library/mac/documentation/Performance/Conceptual/OpenCL_MacProgGuide/InteractingWiththeKernelinOSXOpenCL/InteractingWiththeKernelinOSXOpenCL.html)), but there's a bug (?) in Apple's CPU OpenCL implementation such that you can only have one work item per work group (see [1](http://wiki.tiker.net/OpenCLOddities), [2](http://lists.tiker.net/pipermail/pyopencl/2013-January/001405.html)). Not sure if this is a complete dealbreaker for Mac? Or if this can be checked and some Apple-specific behavior can be done? Where are work group sizes set?

**Comment by hunse** [comment]
Each plan sets its workgroup size individually. So the first thing to do is figure out which plan is throwing this error. Most plans have checks to make sure that this is within the device's max workgroup size, but some of the gemv plans don't, so my guess would be it's one of them. If this is the case, we could probably just use the ref (basic) gemv on macs for everything. This would just mean adding a statement to the beginning of `plan_ragged_gather_gemv.choose_plans` that returns the same as `plan_ref.choose_plans` if we're on a mac (and using a CPU context).

**Comment by tbekolay** [comment]
Cool, I'll try to get that working on my machine. There's some indication online that the Mac CPU OCL implementation doesn't properly report its max workgroup size, so yeah, I'll see if I can get it working!

**Comment by tbekolay** [comment]
OK... so I think I've basically figured this out. Apple's CPU OpenCL implementation is wack and probably we can't support it (but should note this somewhere!) While it advertises that it can do 3-dimensional kernels (`CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS == 3`), it can only have data in the first dimension (`CL_DEVICE_MAX_WORK_ITEM_SIZES == [1024, 1, 1]`). Additionally, it does not support work groups of more than one work item; so, the work group size for every plan must be exactly the work item size.

So, if these commits makes the Apple GPU OpenCL work, then I say we merge it, and revisit Apple CPU support whenever Apple updates its OpenCL implementation. I'll add an error message that checks for a few things and throws an error otherwise... Should we throw this when `nengo_ocl` is imported, or when a `nengo_ocl.sim_ocl.Simulator` instance is created?

**Comment by hunse** [comment]
Cool, good to know. I think the error has to be when we make the `nengo_ocl.Simulator` instance, because we'll have to check the OCL context to see whether they're using the CPU or not.

**Pull request merged**
