### PR TITLE
Reduce testing boiler plate.

### PR DESCRIPTION
**Pull request by jgosmann**
Using improvements to Nengo unit testing in nengo/nengo#711.

It's not necessary anymore (once the Nengo PR is merged) to manully load the Nengo tests etc. Just add a `pytest.ini` file which initializes the additional pytest options `-p nengo.tests.options` and sets simulator and neurons under tests. Unsupported features are set in the `unsupported` attribute of the simulator.

To run all tests (nengo_ocl and nengo against OclSimulator) type `py.test --pyargs nengo .` (The `--pyargs nengo` could be added to `pytest.ini`, but then it's more complicated to just run a subset of tests.)

### CODE REVIEW

**Comment by hunse** [comment]
Got this rebased. The `unsupported` filters aren't working for the way the tests are named when using the args, so that's the main problem right now. I'll try and look at that soon, but probably get a release out first since the tests can still run fine without.

One other thing is that this runs *all* the Nengo tests, even ones that are not Simulator dependent (and therefore don't really need to be run for OCL). Maybe we can change that either here or on Nengo?

**Comment by jgosmann** [comment]
I can look into that.

**Comment by jgosmann** [comment]
> The unsupported filters aren't working for the way the tests are named when using the args, so that's the main problem right now.

I'm not exactly sure what exactly isn't working and what "args" you mean.

> One other thing is that this runs all the Nengo tests, even ones that are not Simulator dependent (and therefore don't really need to be run for OCL). Maybe we can change that either here or on Nengo?

PR nengo/nengo#1052 is addressing that.

**Comment by tbekolay** [comment]
Guessing this branch got rebased but not pushed... I just pushed 9b3092f7d325e so make sure that gets included in the rebased version of the branch!

**Comment by hunse** [comment]
> I'm not exactly sure what exactly isn't working and what "args" you mean.

The `item.nodeid` when checking unsupported tests just has things like `::test_direct`, it doesn't have the full name with the file and everything. So the `fnmatch` expressions I wrote aren't matching, and the unsupported tests aren't getting skipped. Ideas, @jgosmann or @tbekolay?

**Comment by jgosmann** [comment]
Prepending `item.fspath`? (Though, [it can be `None`](http://pytest.org/latest/writing_plugins.html#_pytest.main.Node.fspath), but I don't know when that applies.)

**Comment by hunse** [comment]
There's also `item.location`, which gives some sort of path (I haven't quite figured out how they get it), the line number, and the function name with parameters appended. This should be everything we'd ever need. I'd just like to figure out how to standardize that path to always be from the nengo root directory.

Alternatively, we could use `item.fspath` to get a standardized path. Maybe that's as easy as subtracting out the abs path of the nengo install. But I think either way we might have to do a bit of computation ourselves.

**Comment by jgosmann** [comment]
> Alternatively, we could use item.fspath to get a standardized path. Maybe that's as easy as subtracting out the abs path of the nengo install.

Should be easy with [`relpath`](https://docs.python.org/2/library/os.path.html#os.path.relpath) if we can get the Nengo path.

**Comment by tbekolay** [comment]
You can get the Nengo path with `nengo.__file__`, which will give the path to `nengo/__init__.py(c)`. I'll do a bit of testing to figure out what `item.fspath` gives us...

**Comment by hunse** [comment]
Required changes are now in Nengo master, so once we have a Nengo release this is good to go.

**Pull request merged**
