### PR TITLE
Keep OCL code as ASCII to avoid unicode warnings

### PR DESCRIPTION
**Pull request by hunse**

### CODE REVIEW

**Comment by tbekolay** [comment]
Have you tested this on Python 3? The `decode` calls were added because without them, nengo OCL won't work on Python 3.

**Comment by hunse** [comment]
Ahh, I see...

**Comment by hunse** [comment]
They produce annoying warnings in Python 2, though.

**Comment by tbekolay** [comment]
I guess this needs to be in some helper function that calls `decode` if on Python 3 but not in Python 2?

**Comment by hunse** [comment]
Yeah, I'll do that. I'm just working on getting OCL up and running in Python 3, since apparently I've never done that before.

**Comment by hunse** [comment]
Okay, this should work now.

**Comment by tbekolay** [comment]
Works for me on both Python 2 and 3! Want me to merge?

**Comment by hunse** [comment]
Sure, go for it!

**Pull request merged**
