### PR TITLE
Nengo development

### PR DESCRIPTION
**Pull request by hunse**
This branch is meant to be up to date with the Nengo development branch (``master``). (Whereas the rest of ``nengo_ocl`` should work with the latest Nengo release.)

When a Nengo release happens, this can be merged, but then the branch should be reinstated.

Pinging @tbekolay so he's in on this.

### CODE REVIEW

**Comment by tbekolay** [comment]
Not sure if you saw it, but @drasmuss fixed this in #140 (and I added a fixup for backward compatibility).

Up to you if you want to keep long-living branches around... should people start making PRs on this branch or still on master?

**Comment by hunse** [comment]
Oh, I totally missed that. Or maybe I saw it and wondered "what's that?" and then forgot about it. That's more likely :)

**Comment by hunse** [comment]
Yeah, I almost like the idea of making PRs to this branch. Otherwise, merging #140 will have to wait until the next nengo release, and people wanting to do development here that needs bleeding edge nengo will have to always remember to pull it in. I'll merge #140 into here.

**Comment by tbekolay** [comment]
> merging #140 will have to wait until the next nengo release

Well, as it is now it should be backward compatible so it doesn't need to wait. I think this is kind of necessary anyway, unless versions of Nengo OCL stop supporting older versions of Nengo.

**Comment by hunse** [comment]
Oh, fair, that's true I guess.

**Comment by tbekolay** [comment]
Anyway, totally up to you as maintainer :+1: :rainbow:

**Pull request merged**
