### PR TITLE
Convolution network speedups

### PR DESCRIPTION
**Pull request by hunse**
Speedups for convnets.

### CODE REVIEW

**Comment by LouisCastricato** [comment]
I was working on a similar change for LinearFilter but yours is a lot cleaner looking. It may be possible that [this](https://github.com/nengo/nengo_ocl/pull/97/commits/ff72603d4bcf2d6ca6517b2113d8c1245f4ef723#diff-0abfbfd1c31f6235730d7359cc8514c0R568) is significantly reducing performance since n - i threads have now diverged and will remain idle until the kernel has finished on either all work-groups, or some large amount (I believe the difference depends on the architecture of the card and the OpenCL implementation. Not sure) [[1]](https://tangentvector.wordpress.com/2013/04/12/a-digression-on-divergence/). Since you've greatly increased the number of work groups, you may have also increased the number idling threads. There are ways to work around this. For instance, its possible to have some small number of threads load the data and then launch a kernel of n threads using dynamic parallelism.   Another approach is to forgo local memory and use [textures](https://stackoverflow.com/questions/1959633/opencl-texture-memory) which at times can have equal and perhaps even better performance than local memory. With no need to load the data into a local buffer, you could fairly easily group passes together where all work-groups in a pass have the same n value. Furthermore you could execute them all at once and reuse the same texture. (Note, there are limitations since as you know kernel calls are expensive. If theres a way for you to know the value of n beforehand you could circumvent this limitation)

**Comment by hunse** [comment]
Okay, got the LinearFilter speedups totally working.

Looking at Conv2d again, I got each workgroup doing multiple filters, which really helps to decrease how much memory we have to load since multiple kernels can use each image patch.

I was testing this out on ImageNet, and the networks there (and really many image classification networks) have a lot of filters per layer. In those networks, increasing the filter lsize dimension sped things up, suggesting to me that filters should be the 0th lsize, so that memory accesses when reading filters are coalesced. Maybe have the filter lsize be up to 32.

**Comment by hunse** [comment]
TODO: have to find some sort of blockify for ElementwiseInc and LinearFilter. Right now, because there are so many idle workgroups being allocated, they take forever for large models like Spaun with heterogeneous sizes of things.

**Comment by arvoelke** [comment]
Not sure if this is relevant, but you can see how I combine multiple filters with different time-constants (and even varying order) into a single matrix here: https://github.com/arvoelke/nengolib/blob/master/nengolib/synapses/hetero_synapse.py#L29

**Pull request merged**
