### PR TITLE
Prep for 0.1.0 release

### PR DESCRIPTION
**Pull request by tbekolay**
Note that this is based on #64 so that should be merged first.

This gets Nengo OCL prepped for a release on PyPI. Commits should be pretty self-explanatory, but highlights: updated README, setup.py, and Python 2.6, 2.7, 3.3+ compatibility (the tests run anyhow, but fail on my Mac; should test on a working OCL installation before merging).

If this all looks good (and it, you know, actually works) I'll do a PyPI release upon merge.

### CODE REVIEW

**Comment by tbekolay** [comment]
So shall I do a release now?

**Comment by hunse** [comment]
Yep, I think we're good to go!

**Comment by tbekolay** [comment]
Excellent!

**Comment by tbekolay** [comment]
[Done](https://pypi.python.org/pypi/nengo_ocl)! `pip install nengo_ocl` to test it out.

**Comment by kleinash** [comment]
Awesome stuff :) Congrats guys.

**Pull request merged**
